import Head from 'next/head';
import React from 'react';
import Navbar from '../components/nav/Navbar';
import styles from '../styles/AboutMe.module.scss';

function Contacto() {
  return (
    <>
      <Head>
        <title>Lara con Causa</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Navbar />
      <section className={styles.Aboutme}>
        <div className='contenedor'>
          <h2>Contacto</h2>
          <p>
            lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam,
          </p>
        </div>
      </section>
    </>
  );
}

export default Contacto;
