import Head from 'next/head';
import React from 'react'
import Navbar from '../components/nav/Navbar';
import styles from '../styles/AboutMe.module.scss';

function SobreMi() {
  return (
    <>
        <Head>
        <title>Lara con Causa</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Navbar />
      <section className={styles.Aboutme}>
        <div className="contenedor">
          <h2>Sobre mi</h2>
          <p>
            Soy un desarrollador web con experiencia en el desarrollo de aplicaciones web.
            Me gusta aprender nuevas tecnologías y frameworks para poder desarrollar aplicaciones web modernas.
            Me encanta la programación y la creación de aplicaciones web.
          </p>

    </div>
    </section>
    </>
  )
}

export default SobreMi